### ISSUE TITLE
Не обновляются настройки уведомлений

### ISSUE THREAD

**Issue by bigearsenal** [GolosChain/golos-notifications#63]
## Запрос
![image (1)](https://user-images.githubusercontent.com/6975538/61545481-c71b6b00-aa71-11e9-8701-d08799e24756.png)
## Ответ
OK
## Ответ от options.get
![image](https://user-images.githubusercontent.com/6975538/61545580-f9c56380-aa71-11e9-9154-a836a87ce868.png)
(Не обновляется upvote)

**Comment by bacher** [comment]
@bigearsenal 

Сейчас проверил запросы руками. У меня всё обновилось.

Точно ли поле profile в первом запросе и во втором имеет одно и тоже значение?

Нужны детали запросов, я прям сразу их проверю как скинешь.

**Comment by bacher** [comment]
Проверил на обоих тестнетах, сохраняется.

**Comment by bigearsenal** [comment]
@Bacher 
## options.set
### Request
`{
  "id": 59,
  "method": "options.set",
  "jsonrpc": "2.0",
  "params": {
    "profile": "tst42rfbajss-Simulator-iPhone-SE",
    "push": {
      "lang": "en",
      "show": {
        "upvote": true,
        "downvote": false,
        "transfer": true,
        "reply": true,
        "subscribe": true,
        "unsubscribe": false,
        "mention": true,
        "repost": true,
        "reward": true,
        "curatorReward": true,
        "witnessVote": false,
        "witnessCancelVote": false
      }
    },
    "app": "gls"
  }
}`
(downvote = false)

### Response
`{"jsonrpc":"2.0","id":59,"result":{"status":"OK"}}`


## options.get
### Request
`{
  "id": 19,
  "method": "options.get",
  "jsonrpc": "2.0",
  "params": {
    "profile": "tst42rfbajss-Simulator-iPhone-SE"
  }
}`

### Response
`{
  "jsonrpc": "2.0",
  "id": 19,
  "result": {
    "basic": {},
    "notify": {
      "show": {
        "upvote": true,
        "downvote": true,
        "transfer": true,
        "reply": true,
        "subscribe": true,
        "unsubscribe": true,
        "mention": true,
        "repost": true,
        "reward": true,
        "curatorReward": true,
        "witnessVote": true,
        "witnessCancelVote": true
      }
    },
    "push": {
      "lang": "ru",
      "show": {
        "upvote": true,
        "downvote": true,
        "transfer": true,
        "reply": true,
        "subscribe": true,
        "unsubscribe": true,
        "mention": true,
        "repost": true,
        "reward": true,
        "curatorReward": true,
        "witnessVote": true,
        "witnessCancelVote": true
      }
    }
  }
}`
(downvote=true)

**Comment by bigearsenal** [comment]
Пытался и на дивайсе и на симуляторе.
Не сохраняется.
на 159.69.33.136.
На андройде, как сказал @AlShevelev, тоже не работает
